  // ── Areas ─────────────────────────────────────────────
  // Read off the components. [id, title, view, blurb, rows] — view is which
  // tab it appears under; 'both' shows in each.
  var AREAS = [
    ['panel-default', 'Panel', 'default', 'The left column when you are not editing a step. It asks which situation you are writing content for.', [
      ['context fields', '.demo__fields', 'The dropdowns as a set. Three of them normally, four when your answers describe more than one journey.', 'panelDefault'],
      ['market', 'dropdown 1', 'Which country you are writing for — or "Base", meaning the shared content every country starts from. The help text under it tells you which of the two you are doing.', 'panelDefault'],
      ['user status', 'dropdown 2', 'Who is buying: someone logged out, an existing customer, someone being migrated, or a TVE user. This choice decides which family of journeys you get.', 'panelDefault'],
      ['entry point', 'dropdown 3', 'Where they clicked in from. Narrowed by the answer above — someone being migrated never arrives from an Upgrade button.', 'panelDefault'],
      ['which journey', 'dropdown 4', 'Only appears when your three answers describe more than one journey, and lets you pick between them. Most combinations describe exactly one, so most of the time you never see it.', 'panelDefault'],
      ['user flow', '.uf', 'The journey written out as a numbered list. It is the same information as the tiles on the right, and they share a selection — clicking either opens the same step.', 'panelDefault'],
      ['flow heading', '.uf__title', 'The words "User flow:" above the list.', 'panelDefault'],
      ['flow list', '.uf__list', 'The numbered list itself.', 'panelDefault'],
      ['flow item', '.uf__item', 'One entry in the list, holding the step and the connector line drawn above it.', 'panelDefault'],
      ['flow row', '.uf__row', 'One step in the list. Highlights when selected, and dims when the journey skips it.', 'panelDefault'],
      ['flow dot', '.uf__dot', 'The circle at the left of a row. It holds a tick when that step has fields you can actually edit — today only Subscription does, and the list says so rather than pretending otherwise.', 'panelDefault'],
      ['flow name', '.uf__name', 'The step name.', 'panelDefault'],
      ['flow skip tag', '.uf__tag', 'A small "seeded" or "not here" on steps this journey skips. "Seeded" means the entry point already answered that question; "not here" means the step does not exist in this journey.', 'panelDefault'],
      ['flow edit button', '.uf__edit', 'The pencil that opens a step. Only on steps that have something to edit.', 'panelDefault'],
      ['flow connector', '.uf__link', 'The short line drawn between one row and the next, so the list reads as a sequence.', 'panelDefault'],
      ['reset progress', '.demo__reset', 'The link at the bottom. Throws away your local edits and reloads the content the app shipped with.', 'panelDefault'],
    ]],
    ['preview-default', 'Preview', 'default', 'The right column when you are not editing. Shows the whole journey at once.', [
      ['frames block', '.jf', 'The journey overview as a whole.', 'overview'],
      ['row caption', '.jf__caption', 'The line above the tiles: how many screens across how many steps.', 'overview'],
      ['drag hint', '.jf__hint', 'The reminder that you can drag a step sideways to reorder it, or hold alt and use the arrow keys.', 'overview'],
      ['reordered chip', '.jf__reordered', 'A small marker that appears once your order no longer matches the order drawn in Figma.', 'overview'],
      ['reset order', '.jf__reset', 'Puts the steps back into the Figma order.', 'overview'],
      ['frames row', '.jf__row', 'The row of screens that scrolls sideways.', 'overview'],
      ['step group', '.jf__step', 'One step together with all its screens. This is the block you drag when reordering.', 'overview'],
      ['step label', '.jf__step-name', 'The step name above its screens.', 'overview'],
      ['state count', '.jf__states', 'Says "· 3 states" when a step is drawn more than one way.', 'overview'],
      ['skip tag', '.jf__tag', 'A "seeded" or "not here" marker explaining why a step shows nothing.', 'overview'],
      ['tiles strip', '.jf__tiles', 'The screens belonging to one step, side by side.', 'overview'],
      ['tile cell', '.jf__cell', 'One tile and the caption under it, kept together so the caption tracks the screen it names.', 'overview'],
      ['step tile', '.jf__tile', 'One screen. Click it to edit that step.', 'overview'],
      ['tile number', '.jf__num', 'Where the step falls in the flow, beside its name. A step drawn three ways occupies three numbers and shows the span — 6–8 — so the last number in the row still equals the journey’s screen count.', 'overview'],
      ['thumbnail', '.jf__thumb', 'A live miniature of the real screen, built from your actual content. Sized to the proportions of a 375 by 812 phone.', 'overview'],
      ['thumbnail scaler', '.jf__thumb-scale', 'The layer inside the thumbnail that shrinks the screen. The screen renders at full size and this scales it down, so the miniature is the real thing rather than a separate small version that could drift from it.', 'overview'],
      ['phone status bar', '.jf__status', 'The iOS status bar across the top of a tile — the iOS/android component from Figma, drawn at the tile’s scale. Static, so it holds still while the screen scrolls beneath it; each frame’s own status bar is clipped off the export and this one drawn in its place.', 'overview'],
      ['status time', '.jf__status-time', 'The clock. Always 9:41, as the design has it.', 'overview'],
      ['notch spacer', '.jf__status-island', 'The gap the Dynamic Island sits in. It draws nothing and reserves 124px, which is why the clock sits left of centre rather than in the middle.', 'overview'],
      ['status levels', '.jf__status-levels', 'The signal, wifi and battery group at the right.', 'overview'],
      ['signal icon', '.jf__status-cell', 'Cellular bars, exported from the component.', 'overview'],
      ['wifi icon', '.jf__status-wifi', 'Wifi, exported from the component.', 'overview'],
      ['battery icon', '.jf__status-battery', 'Battery, exported from the component.', 'overview'],
      ['browser chrome', '.jf__chrome', 'The Safari address bar at the foot of a tile — the .Safari, iOS component from Figma, drawn at the tile’s scale so it is the design’s own geometry rather than an approximation. It is pinned rather than left in the picture, so it holds still while the screen scrolls behind it; each frame’s own bar is clipped off and this one drawn in its place.', 'overview'],
      ['chrome button', '.jf__chrome-btn', 'One of the two round 44px buttons either side of the address — back on the left, menu on the right.', 'overview'],
      ['address pill', '.jf__url', 'The rounded bar holding the site icon, the domain and the reload arrow.', 'overview'],
      ['site settings icon', '.jf__url-icon', 'The page-settings glyph at the left of the pill, exported from the Figma component.', 'overview'],
      ['address text', '.jf__url-text', 'The domain. Centred in the whole pill rather than in the gap between the icons, so a longer name stays centred.', 'overview'],
      ['reload icon', '.jf__url-reload', 'The refresh arrow at the right of the pill, exported from the Figma component.', 'overview'],
      ['browser menu', '.jf__dots', 'The three dots in the right-hand button. iOS draws it as an SF Symbol, which has no exported asset, so it is three dots at the symbol’s own size.', 'overview'],
      ['screen', '.jf__screen', 'Everything above the address bar, taking all the height the bar does not. A screen taller than that scrolls here rather than shrinking to fit — Checkout is 1321 tall, and fitting it would make the payment rows too small to read.', 'overview'],
      ['page clip', '.jf__page', 'Holds the exported picture and crops the Safari bar off its foot. Its height is the frame’s own height less that bar, at the tile’s scale, so it is set per screen rather than in the stylesheet.', 'overview'],
      ['screen artwork', '.jf__art', 'The screen exported from Figma, shown on steps that have not been built yet. Full tile width, natural height. It is a picture, so it does not change when you edit content — that is how you tell a built screen from one still to come.', 'overview'],
      ['frame name', '.jf__frame', 'The Figma frame name. The last resort, for a screen with neither a component nor an exported frame.', 'overview'],
      ['state label', '.jf__state', 'Which version of the screen a tile is — “standard”, “ultimate”. Sits under the tile rather than over it, where it covered the design it was labelling.', 'overview'],
    ]],
    ['actions-default', 'Action buttons', 'default', 'Two buttons at the top right when you are not editing a step.', [
      ['preview button', 'button 1 · secondary', 'Hides the panel so the preview fills the window. Press it again — it now says "Show panel" — to bring the panel back.', 'actionsDefault'],
      ['export button', 'button 2 · tertiary', 'Says "Export JSON". Downloads all the content as a file. Worth knowing: this is the shape this app stores, not yet the shape the live rule engine reads.', 'actionsDefault'],
    ]],
    ['panel-edit', 'Panel', 'edit', 'The left column once you have opened a step. Six groups of fields, all scoped to one country, one storefront and one way of paying.', [
      ['step heading', '.demo__head', 'The line at the top of the panel: the back arrow and the step title together.', 'panelEdit'],
      ['back arrow', '.demo__back', 'The chevron at the top left. It is the only thing on that line you can click, and it takes you back to the journey.', 'panelEdit'],
      ['step title', '.demo__step-title', 'The name of the step you have open. A heading, not a control — the arrow beside it is what takes you back.', 'panelEdit'],
      ['field group', '.demo__group', 'One titled block of fields. There are six of them.', 'panelEdit'],
      ['group title', '.demo__group-title', 'The heading on a group. Pricing adds the currency to its heading.', 'panelEdit'],
      ['plans group', 'group 1 · Plans', 'Which plan you are editing.', 'panelEdit'],
      ['header group', 'group 2 · Tier Name', 'The words at the top of the card.', 'panelEdit'],
      ['pricing group', 'group 3 · Pricing', 'What it costs and how you pay.', 'panelEdit'],
      ['add-on group', 'group 4 · Add-on', 'An extra product attached to the plan.', 'panelEdit'],
      ['competitions group', 'group 5 · Competitions', 'Which competition logos show on the card.', 'panelEdit'],
      ['features group', 'group 6 · Features', 'The bullet list of what you get.', 'panelEdit'],
    ]],
    ['group-plans', 'Plans group', 'edit', 'Group 1. Picks which plan the rest of the panel is about.', [
      ['plan tabs', '.ed-tabs', 'The row of plan names you switch between. Not a setting — it chooses which plan the whole panel below is editing.', 'groupPlans'],
      ['plan tab', '.ed-tab', 'One plan name. Dimmed when that plan is not sold in the situation you picked, and hovering it tells you why.', 'groupPlans'],
      ['plan not sold note', '.ed-absent', 'Appears when you are looking at a plan this situation does not sell. It says why, and reassures you that your edits still apply everywhere the plan does sell.', 'groupPlans'],
      ['no plans message', '.ed-placeholder · plans', 'What the panel says instead of a form when the content has no plans at all.', 'groupPlans'],
    ]],
    ['group-header', 'Header group', 'edit', 'Group 2. The words at the top of the card.', [
      ['badge field', 'Badge', 'The words on the badge. Editable — type what it should say. Whether a badge shows at all is still the Highlighted Tier switch’s call, and leaving this empty falls back to “BEST EXPERIENCE” rather than shipping a blank ribbon.', 'groupHeader'],
      ['ultimate toggle', 'Highlighted Tier', 'The switch that makes this the standout plan: gold outline, badge and gold button. Only one plan in a set may have it.', 'groupHeader'],
      ['plan name field', 'Tier name', 'The public name of the plan. One value that appears in three places — the card heading, the button, and the add-on label.', 'groupHeader'],
      ['AI pill', '.ai-pill', 'The AI half of the source tabs — the product’s own pill, with the sparkle and the yellow-to-purple gradient edge. Two stacked backgrounds make that edge: a flat fill clipped to the padding box, the gradient clipped to the border box, showing through a transparent 1px border. Unselected it dims rather than changing shape.', 'groupHeader'],
      ['AI sparkle', '.ai-pill__mark', 'The four-point glyph inside the AI pill. A flex box rather than a plain wrapper, so the icon centres instead of resting on a text baseline.', 'groupHeader'],
      ['source tabs', '.ed-source', 'Two tabs hard right above a copy field: AI or Custom. Used twice — over the Description and over the Price explainer. Custom is the default, and it is what copy written before the choice existed counts as. Choosing AI hands that field to the assistant and makes it read-only here.', 'groupHeader'],
      ['description field', 'Description', 'The paragraph under the plan name. Type the whole thing; never shorten it yourself, because the card measures the space and adds "… more" where it needs to.', 'groupHeader'],
    ]],
    ['group-pricing', 'Pricing group', 'edit', 'Group 3. What it costs. Every price here belongs to one way of paying.', [
      ['standard price field', 'Full price', 'The undiscounted price, in the currency of the country you picked.', 'groupPricing'],
      ['price unit field', 'Price per', 'Everything after the slash — the “month” in “$29.99/month”. It belongs to the way of paying rather than to this plan, so what you write here reads the same on every plan priced that way. Leave it and it uses the name of the cadence itself, in lower case.', 'groupPricing'],
      ['apply discount toggle', 'Apply discount', 'Turns on a promotional price. Switching it on fills in a starting discount price for you, twenty percent under standard, which you can then change.', 'groupPricing'],
      ['discount price field', 'Discount price', 'The promotional price. Only appears when the discount is on, and it turns red if you type a number at or above the standard price, because that is not a discount.', 'groupPricing'],
      ['button field', 'Button', 'What the card’s button says, written out. It sits under the price explainer and is not part of the discount — every plan has a button. Leave it empty and it falls back to “Get” and the plan’s name.', 'groupPricing'],
      ['button savings menu', 'Add the saving', 'Only with a discount, because only then is there a saving to name. It offers the plain wording and the two that add the saving, as money or as a percentage, each shown as the button it produces. Picking one writes it into the Button field above, where you can then edit it.', 'groupPricing'],
      ['price explainer field', 'Price explainer', 'The sentence under the price — “For the first 3 months, then $34.99/monthly”. Only appears where there is a discount to explain. Editable, with the same AI or Custom choice as the Description; empty falls back to the sentence built from the intro months, the full price and the cadence.', 'groupPricing'],
      ['not sold at this cadence', '.ed-placeholder · pricing', 'Replaces the price fields when this plan is not sold at the chosen cadence. It says plainly that this is a fact about the plan, not something missing that you need to fill in.', 'groupPricing'],
    ]],
    ['group-addon', 'Add-on group', 'edit', 'Group 4. An extra product attached to this price. Hidden for now — the group is not in the panel and the panel is not on the card, both off one switch (SHOW_ADDON). The fields and the catalogue are intact underneath.', [
      ['add-on field', 'Add-on', 'Which extra product goes with this plan, and whether it is sold separately or included in the price. Each add-on appears twice in the list, once as "sold" and once as "bundled" — it can never be both.', 'groupAddon'],
      ['paid-for field', 'How it is paid for', 'Only when the add-on is sold rather than bundled. Either a one-off payment, or a discount code the customer redeems.', 'groupAddon'],
      ['discount percent field', 'Discount percent', 'Only when the add-on is sold with a discount code. How much off, as a number between 1 and 99.', 'groupAddon'],
      ['no offer note', '.ed-placeholder · add-on', 'Replaces the add-on fields when the plan has no price at this cadence, since there is nothing to attach an add-on to.', 'groupAddon'],
    ]],
    ['group-comps', 'Competitions group', 'edit', 'Group 5. Which competitions the plan carries, in what order, and what the popup says about each one.', [
      ['competitions list', '.ed-comps', 'The competitions on this plan, one under the other in the order they sit on the card.', 'groupComps'],
      ['competition entry', '.ed-comp', 'One competition: its handle at the top, then its name and the line the popup shows.', 'groupComps'],
      ['drag handle', '.ed-comp__head', 'The strip you drag to move a competition up or down. Only this strip drags, so the fields below it still let you select text. With it focused, alt and the up or down arrow moves it one place.', 'groupComps'],
      ['position number', '.ed-comp__pos', 'Where it sits in the order. 1 is the first logo on the card.', 'groupComps'],
      ['row logo', '.ed-comp__logo', 'The artwork, so you can tell the rows apart at a glance.', 'groupComps'],
      ['row name', '.ed-comp__name', 'The competition name, repeated on the handle so the row still reads when you are dragging it.', 'groupComps'],
      ['remove competition', '.ed-comp__remove', 'Takes it off this plan. The competition itself stays in the library for other plans.', 'groupComps'],
      ['competition name field', 'Competition name', 'What it is called, on the card and in the popup. It belongs to the competition rather than to this plan, so changing it changes it everywhere that competition appears.', 'groupComps'],
      ['competition description field', 'Description', 'The line under the name in the "All features & content" popup. Like the name, it belongs to the competition rather than to this plan.', 'groupComps'],
      ['competitions total field', 'Total number of competitions', 'How many competitions the plan carries in total, which is usually more than the logos shown. The card works out the "+5" tile from this number minus the logos on display.', 'groupComps'],
    ]],
    ['group-features', 'Benefits group', 'edit', 'Group 6. The bullet list of what you get. Five is the most a card shows, so five is the most you can add.', [
      ['benefit row', '.demo__feature', 'One line of the list, with its picker and — when the line is a custom one — the box to type it in and its icon.', 'groupFeatures'],
      ['benefit picker', 'Benefit 1, 2, 3…', 'Choose a benefit from the shared library, or "Write a custom benefit…" at the bottom. Every entry shows its icon beside the words, because the icon is half of what tells two similar lines apart. Retired lines are still listed, marked "(retired)", so old content keeps working.', 'groupFeatures'],
      ['benefit picker field', '.ed-pick', 'The picker as a whole — its label, the current benefit, and the list when it is open.', 'groupFeatures'],
      ['benefit picker label', '.ed-pick__label', 'The words "Benefit 1", "Benefit 2" and so on above the picker.', 'groupFeatures'],
      ['benefit picker value', '.ed-pick__value', 'The closed picker, showing the icon and words of the benefit currently chosen. Click it to open the list.', 'groupFeatures'],
      ['benefit picker text', '.ed-pick__text', 'The words in the picker. A benefit too long for the row is cut with an ellipsis rather than wrapping.', 'groupFeatures'],
      ['benefit picker menu', '.ed-pick__menu', 'The open list of benefits.', 'groupFeatures'],
      ['benefit option', '.ed-pick__option', 'One benefit in the open list: its icon, then its words.', 'groupFeatures'],
      ['benefit option icon', '.ed-pick__mark', 'The icon slot on the left of each option. It stays there even for the one line with no icon, so the words line up down the list.', 'groupFeatures'],
      ['icon chooser label', '.ed-icons__label', 'The word "Icon" above the choices.', 'groupFeatures'],
      ['benefit text field', 'Benefit', 'Where you type a custom benefit. What you write is saved into the shared library, so it can be reused on other plans.', 'groupFeatures'],
      ['icon chooser', '.ed-icons', 'The icon for a custom benefit — only custom ones need it, since a benefit from the library arrives with the icon it was paired with.', 'groupFeatures'],
      ['suggest icon', '.ed-icons__head', 'The "Suggest" button beside the word Icon. It asks the assistant which of the icons below suits what you wrote, and picks it. It can only answer with one of them, so the worst it can do is choose wrongly and you click another.', 'groupFeatures'],
      ['icon options', '.ed-icons__row', 'The icons you can choose from. The current one carries a yellow outline.', 'groupFeatures'],
      ['icon option', '.ed-icons__option', 'One icon. Hovering says what it means.', 'groupFeatures'],
      ['suggestion note', '.ed-icons__note', 'What the assistant chose and why, or why it could not.', 'groupFeatures'],
      ['remove benefit', '.demo__feature-remove', 'Takes that line off this plan. It stays in the library.', 'groupFeatures'],
      ['add benefit', 'Add benefit', 'Adds another line. It switches off at five and says so, rather than going quiet.', 'groupFeatures'],
    ]],

    ['flow-shared', 'Journey screens — shared parts', 'edit', 'The pieces every screen after the plan picker is built from. A screen shows only what sits between the phone\u2019s status bar and the browser\u2019s address bar: those two belong to the device, and the frame in the overview draws them around this.', [
      ['screen frame', '.fl', 'One journey screen, 375 wide — the width the design draws them at.', 'flowShared'],
      ['screen header', '.fl__header', 'The bar under the status bar: back arrow, title, DAZN mark, and the gold rule under it that shows how far through the journey you are.', 'flowShared'],
      ['screen back arrow', '.fl__back', 'The chevron at the left of the header.', 'flowShared'],
      ['screen title', '.fl__title', 'The centred title. Editable per screen — it is the only thing in the header that changes.', 'flowShared'],
      ['screen brand', '.fl__brand', 'The DAZN mark at the right of the header.', 'flowShared'],
      ['screen body', '.fl__body', 'Everything under the header, with 16 down each side and 24 top and bottom.', 'flowShared'],
      ['screen field', '.fl__field', 'A text field at rest, 56 tall. With something typed it shows the name above the value; empty, the name sits where the value would.', 'flowShared'],
      ['field name', '.fl__field-label', 'What the field is called.', 'flowShared'],
      ['field value', '.fl__field-value', 'What has been typed into it.', 'flowShared'],
      ['field row', '.fl__field-row', 'The row inside a field that carries a mark beside the text.', 'flowShared'],
      ['field contents', '.fl__field-body', 'The name and value stacked, so they read as one thing beside any marks.', 'flowShared'],
      ['field mark', '.fl__field-icon', 'An icon at either end of a field.', 'flowShared'],
      ['field pair', '.fl__group', 'Two fields sharing one outer rounding — first and last name, for instance.', 'flowShared'],
      ['screen button', '.fl__cta', 'A button on a journey screen. White by default; plain text for a second, quieter action; grey while something is happening.', 'flowShared'],
      ['screen divider', '.fl__divider', 'A rule with a word in the middle of it, usually \u201cor\u201d.', 'flowShared'],
    ]],
    ['flow-cadence', 'Cadence screen', 'edit', 'Group 1 of the flow. Which way of paying you choose.', [
      ['ways to pay', '.fl-cadence', 'The two options and the button under them.', 'flowCadence'],
      ['pay options', '.fl-cadence__options', 'The options as a stack.', 'flowCadence'],
      ['pay option', '.fl-cadence__option', 'One way of paying. The chosen one carries a gold edge.', 'flowCadence'],
      ['option radio', '.fl-cadence__radio', 'The circle showing which one is chosen.', 'flowCadence'],
      ['option text', '.fl-cadence__text', 'The name, the note and the price together.', 'flowCadence'],
      ['option name', '.fl-cadence__name', 'What the option is called. Painted gold on the chosen one.', 'flowCadence'],
      ['option note', '.fl-cadence__note', 'The grey line under the name.', 'flowCadence'],
      ['option price', '.fl-cadence__price', 'The amount and how often you pay it.', 'flowCadence'],
      ['option amount', '.fl-cadence__amount', 'The number.', 'flowCadence'],
      ['option unit', '.fl-cadence__unit', 'What follows the slash — \u201cyear\u201d, \u201cmonth\u201d.', 'flowCadence'],
      ['option ribbon', '.fl-cadence__badge', 'The gold corner ribbon. Empty text draws no ribbon.', 'flowCadence'],
      ['cadence footnote', '.fl-cadence__footnote', 'The line with the information mark under the button.', 'flowCadence'],
    ]],
    ['flow-auth', 'Login screen', 'edit', 'Group 2 of the flow. Signing in, or signing up.', [
      ['login screen', '.fl-auth', 'The whole screen under the header.', 'flowAuth'],
      ['login mark', '.fl-auth__mark', 'The DAZN mark at the top.', 'flowAuth'],
      ['login title block', '.fl-auth__title', 'The heading and the line under it.', 'flowAuth'],
      ['login heading', '.fl-auth__heading', 'The big line.', 'flowAuth'],
      ['login subheading', '.fl-auth__sub', 'The grey line under it.', 'flowAuth'],
      ['login notice', '.fl-auth__notice', 'The grey box for people who already have an account.', 'flowAuth'],
      ['notice heading', '.fl-auth__notice-title', 'The bold line in the box, with its information mark.', 'flowAuth'],
      ['notice body', '.fl-auth__notice-body', 'The line under it.', 'flowAuth'],
      ['login form', '.fl-auth__form', 'The email field, the button, the divider and the provider buttons.', 'flowAuth'],
      ['provider buttons', '.fl-auth__providers', 'Apple, Google and Facebook as a stack.', 'flowAuth'],
      ['provider button', '.fl-auth__provider', 'One provider button, with that provider\u2019s own mark.', 'flowAuth'],
    ]],
    ['flow-account', 'Account setup screen', 'edit', 'Group 3 of the flow, drawn three ways: empty, filled, and confirmed. The checklist under the password appears once there is a password to check.', [
      ['account screen', '.fl-account', 'The whole screen under the header.', 'flowAccount'],
      ['account fields', '.fl-account__fields', 'The four sections stacked.', 'flowAccount'],
      ['account section', '.fl-account__block', 'One section: its heading and the fields under it.', 'flowAccount'],
      ['account section heading', '.fl-account__heading', 'The bold line over a section.', 'flowAccount'],
      ['password checklist', '.fl-account__rules', 'What the password has to contain. Only on the filled and confirmed screens.', 'flowAccount'],
      ['checklist heading', '.fl-account__rules-title', 'The line over the rules.', 'flowAccount'],
      ['checklist rule', '.fl-account__rule', 'One rule, with its tick.', 'flowAccount'],
      ['consent box', '.fl-account__consent', 'The bordered box holding the marketing text and its switch.', 'flowAccount'],
      ['consent text', '.fl-account__consent-body', 'The marketing wording.', 'flowAccount'],
      ['consent switch', '.fl-account__switch', 'The green toggle.', 'flowAccount'],
      ['consent knob', '.fl-account__knob', 'The white circle inside it.', 'flowAccount'],
      ['consent note', '.fl-account__note', 'The line under the box.', 'flowAccount'],
    ]],
    ['flow-zip', 'ZIP code screen', 'edit', 'Group 4 of the flow, drawn three ways: default, edit, and edit results. The teams appear only on the results screen.', [
      ['zip screen', '.fl-zip', 'The whole screen under the header.', 'flowZip'],
      ['zip intro', '.fl-zip__intro', 'The heading and the paragraph under it.', 'flowZip'],
      ['zip heading', '.fl-zip__heading', 'The big line.', 'flowZip'],
      ['zip body', '.fl-zip__body', 'The paragraph explaining what the ZIP code is for.', 'flowZip'],
      ['zip results', '.fl-zip__results', 'The teams the ZIP code resolves to.', 'flowZip'],
      ['zip results heading', '.fl-zip__results-label', 'The line over the teams. Figma still carries a placeholder here rather than copy.', 'flowZip'],
      ['zip team grid', '.fl-zip__grid', 'The teams, five to a row.', 'flowZip'],
      ['zip team', '.fl-zip__logo', 'One team badge, 59 square. They come from the same library the cards use, so this screen cannot show a team the cards do not carry.', 'flowZip'],
    ]],
    ['flow-checkout', 'Checkout screen', 'edit', 'Group 5 of the flow, drawn four ways: empty, filled, payment process, and payment verified.', [
      ['checkout screen', '.fl-checkout', 'The whole screen under the header.', 'flowCheckout'],
      ['checkout note', '.fl-checkout__note', 'The line at the top about encryption.', 'flowCheckout'],
      ['purchase summary', '.fl-checkout__summary', 'The bordered card showing what is being bought.', 'flowCheckout'],
      ['summary heading', '.fl-checkout__summary-head', 'The plan name and the Change button.', 'flowCheckout'],
      ['summary title', '.fl-checkout__summary-title', 'The plan name.', 'flowCheckout'],
      ['change button', '.fl-checkout__change', 'The small button beside it.', 'flowCheckout'],
      ['summary line', '.fl-checkout__line', 'One row of the summary: a label and an amount.', 'flowCheckout'],
      ['line label', '.fl-checkout__line-label', 'The left half. Rows about a date carry a calendar mark and read quieter.', 'flowCheckout'],
      ['line amount', '.fl-checkout__line-value', 'The right half.', 'flowCheckout'],
      ['line unit', '.fl-checkout__line-unit', 'What follows the slash on a row that has one.', 'flowCheckout'],
      ['renewal note', '.fl-checkout__renewal', 'The small print at the foot of the summary.', 'flowCheckout'],
      ['payment card', '.fl-checkout__methods', 'The bordered card holding the ways to pay.', 'flowCheckout'],
      ['payment option', '.fl-checkout__method', 'One way to pay: its radio, its name, and the marks for it.', 'flowCheckout'],
      ['payment option name', '.fl-checkout__method-name', 'The radio and the name together.', 'flowCheckout'],
      ['payment marks', '.fl-checkout__marks', 'The card or wallet logos at the right of a row.', 'flowCheckout'],
      ['more cards chip', '.fl-checkout__overflow', 'The \u201c+4\u201d after the card marks.', 'flowCheckout'],
      ['card details', '.fl-checkout__details', 'The card fields, the small print and the pay button, under the cards option.', 'flowCheckout'],
      ['field pair row', '.fl-checkout__pair', 'Expiry date and CVC side by side.', 'flowCheckout'],
      ['legal text', '.fl-checkout__legal', 'The terms under the fields.', 'flowCheckout'],
      ['option spacer', '.fl-checkout__spacer', 'The gap the design leaves between two of the payment rows.', 'flowCheckout'],
      ['promo row', '.fl-checkout__promo', 'The bordered row at the bottom.', 'flowCheckout'],
      ['promo label', '.fl-checkout__promo-label', 'What it says.', 'flowCheckout'],
    ]],
    ['flow-ready', 'Confirmation screen', 'edit', 'Group 6 of the flow. The last screen before the app.', [
      ['confirmation screen', '.fl-ready', 'The whole screen under the header, centred in what is left of it.', 'flowReady'],
      ['confirmation content', '.fl-ready__content', 'The circles, the heading and the line under it.', 'flowReady'],
      ['team circles', '.fl-ready__logos', 'The row of overlapping team badges.', 'flowReady'],
      ['team circle', '.fl-ready__logo', 'One badge. The middle one is drawn larger, which is what makes the row read as a group.', 'flowReady'],
      ['confirmation heading', '.fl-ready__title', 'The big line.', 'flowReady'],
      ['confirmation body', '.fl-ready__body', 'The line under it.', 'flowReady'],
      ['confirmation buttons', '.fl-ready__ctas', 'The two buttons at the bottom.', 'flowReady'],
    ]],
    ['preview-edit', 'Preview', 'edit', 'The right column once you have opened a step. Shows just that one screen.', [
      ['state row', '.jy__screens', 'The step’s states side by side — the same shape the plan picker takes for its three cards, and the shape the Figma section lays them out in. It scrolls sideways when there are more than fit.', 'stepview'],
      ['one state', '.jy__screen', 'One state: the screen and the name under it.', 'stepview'],
      ['state name', '.jy__screen-name', 'Which state this one is — empty, filled, confirmed, and so on.', 'stepview'],
      ['step preview', '.jy', 'The step preview as a whole.', 'stepview'],
      ['entry line', '.jy__entry', 'The line of context above the screen.', 'stepview'],
      ['step name', '.jy__step-name', 'Which step you are looking at.', 'stepview'],
      ['step meta', '.jy__meta', 'Where this step sits in the flow, what the customer clicked to get here, and how many plans are in the set.', 'stepview'],
      ['inbound seeds', '.jy__seeds', 'What the entry point already decided before the customer got here — so you know which questions this screen no longer has to ask.', 'stepview'],
      ['viewport', '.jy__viewport', 'The frame the real screen renders inside. Sized to a 375-wide phone when the set is a mobile one.', 'stepview'],
      ['placeholder screen', '.jy__placeholder', 'What you see instead of a real screen when that step has not been built yet. It tells you everything known about the screen so far.', 'stepview'],
      ['placeholder frame name', '.jy__frame', 'The name of the Figma frame this screen will be built from.', 'stepview'],
      ['placeholder states', '.jy__states', 'The different versions this screen is drawn in.', 'stepview'],
      ['placeholder gates', '.jy__requires', 'The conditions the real product checks before showing this screen.', 'stepview'],
      ['placeholder note', '.jy__note', 'A free note about the screen. The same style also carries the message when a journey has no steps in the chosen country.', 'stepview'],
      ['placeholder warning', '.jy__todo', 'The line reading "Placeholder — this screen isn’t built yet."', 'stepview'],
    ]],
    ['actions-edit', 'Action buttons', 'edit', 'The buttons at the top right once you have opened a step. They are the review, in the order it happens: hand it over, then have it approved. Whichever one is live is the solid button; the step behind it drops back to a plain one rather than disappearing, so you can still see where you are in the sequence. To leave a step, use the arrow at the top of the panel.', [
      ['ready for review button', 'button 1 · Ready for review', 'Hands the content to product and UX. Switched off until every situation passes its rules — the gate to the left says how many are still failing — and switched off again once you have asked, since you cannot ask twice.', 'actionsEdit'],
      ['approved button', 'button 2 · Approved', 'Records that product and UX said yes, and publishes to the shared copy at the same time. Only available while the content is with them.', 'actionsEdit'],
      ['evaluate button', 'button 3 · Evaluate performance', 'The AI coach. Not connected to anything yet, so it is switched off and says so rather than answering a click with nothing.', 'actionsEdit'],
    ]],
    ['card', 'The card', 'both', 'The plan card itself. This is what renders in the preview and inside every thumbnail.', [
      ['preview area', '.acq-preview', 'The box the cards sit in. It is also what the "All features & content" popup covers — the popup is sized to the phone, not to your browser window.', 'card'],
      ['set scroller', '.acq-set-scroll', 'The scrolling wrapper around the row of cards, for when they do not all fit.', 'card'],
      ['card set', '.acq-set', 'The row of cards. It measures all of them and gives them one shared description height and one shared card height, so they line up.', 'card'],
      ['card', '.acq-card', 'One plan card. Gains a gold outline when it is the Ultimate one.', 'card'],
      ['badge', '.acq-card__eyebrow', 'The "BEST EXPERIENCE" label on the top edge. Comes from the Ultimate toggle, and only one card in a set can have it.', 'card'],
      ['card body', '.acq-card__body', 'Everything inside the card except the footer.', 'card'],
      ['card header', '.acq-card-header', 'The plan name and description together.', 'card'],
      ['plan name', '.acq-card-header__title', 'The name at the top. Gets the gold treatment on the Ultimate card.', 'card'],
      ['description', '.acq-card-header__description', 'The paragraph. Measured against the other cards and cut to the shared height.', 'card'],
      ['more button', '.acq-card-header__more', 'The "… more" link, which only appears when the description is too long to fit.', 'card'],
      ['card divider', '.acq-card__divider', 'The line between the header and the price.', 'card'],
      ['pricing', '.acq-pricing', 'The whole price block.', 'card'],
      ['price caption', '.acq-pricing__caption', 'The small "Starts at" above the number.', 'card'],
      ['price row', '.acq-pricing__row', 'The line holding the price and the struck-through price side by side.', 'card'],
      ['price', '.acq-pricing__price', 'The number people actually read.', 'card'],
      ['crossed price', '.acq-pricing__crossed', 'The struck-through standard price, shown only when there is a discount.', 'card'],
      ['price explainer', '.acq-pricing__extra', 'The sentence under the price explaining the offer.', 'card'],
      ['instalment line', '.acq-pricing__installment', 'The line spelling out the monthly instalment on an annual plan.', 'card'],
      ['plan CTA', '.acq-plan-cta', 'The savings line and the Get button together as one block.', 'card'],
      ['savings ribbon', '.acq-plan-cta__eyebrow', 'The "Save up to €108 / year" line. Worked out from the two prices, not typed.', 'card'],
      ['get button', '.acq-plan-cta__stack', 'The button that starts the purchase. Gold on the Ultimate card.', 'card'],
      ['logo tiles', '.acq-logo-tiles', 'The row of competition logos, in the order they were picked.', 'card'],
      ['logo tile', '.acq-logo-tiles__tile', 'One competition logo.', 'card'],
      ['overflow tile', '.acq-logo-tiles__tile--overflow', 'The "+5" tile. Worked out from the total you entered minus the logos on show — not something you pick.', 'card'],
      ['add-on panel', '.acq-addon', 'The block advertising the extra product.', 'card'],
      ['features list', '.acq-features', 'The bullet list as a block.', 'card'],
      ['card feature row', '.acq-feature', 'One bullet: an icon and a line of text.', 'card'],
      ['feature text', '.acq-feature__text', 'The words of one bullet.', 'card'],
      ['card footer', '.acq-card__footer', 'The "All features & content" bar across the bottom, edge to edge.', 'card'],
    ]],
    ['card-addon', 'The card — add-on panel', 'both', 'The inside of the add-on block on the card. Hidden for now, with the rest of the add-on — these are what it draws when it comes back.', [
      ['add-on content', '.acq-addon__content', 'The artwork and the words together, above the divider.', 'cardAddon'],
      ['add-on artwork', '.acq-addon__image', 'The picture of the add-on.', 'cardAddon'],
      ['add-on text', '.acq-addon__text', 'The title and subtitle stacked beside the artwork.', 'cardAddon'],
      ['add-on title', '.acq-addon__title', 'Its name.', 'cardAddon'],
      ['add-on subtitle', '.acq-addon__subtitle', 'The line under the name.', 'cardAddon'],
      ['add-on status', '.acq-addon__status', 'How it is offered. Three versions: included in the price, a payment, or a discount code — and the styling differs for each.', 'cardAddon'],
      ['add-on divider', '.acq-addon__divider', 'The line inside the block.', 'cardAddon'],
      ['add-on footer', '.acq-addon__footer', 'The bottom row of the block.', 'cardAddon'],
    ]],
    ['card-details', 'The card — “All features & content” popup', 'both', 'What opens when you click "All features & content" at the bottom of a card, or the "… more" link in its description. Everything on it comes from the card behind it — the same title, the same CTA, the same competitions and feature lines. Two things it shows that the card cannot: the description in full, and every competition, including the ones the card hides behind "+5".', [
      ['popup', '.acq-details', 'The popup as a whole — the dimming layer and the panel together.', 'cardDetails'],
      ['dimming layer', '.acq-details__scrim', 'The dark wash over the cards behind. Clicking it closes the popup, as does Escape.', 'cardDetails'],
      ['popup panel', '.acq-details__dialog', 'The panel itself, 600 tall and 4 clear of the card down each side — the proportions it is drawn at in Figma. It shrinks if the window is too short to show all of it.', 'cardDetails'],
      ['close button', '.acq-details__close', 'The X in the top right corner. The circle you see is 24; the part that answers a click is the 48 square around it.', 'cardDetails'],
      ['popup body', '.acq-details__body', 'Everything above the button. It does not scroll — only the list inside it does.', 'cardDetails'],
      ['popup head', '.acq-details__head', 'The plan name, description and tabs as one block. It stays put while the list scrolls under it.', 'cardDetails'],
      ['popup intro', '.acq-details__intro', 'The plan name and description at the top.', 'cardDetails'],
      ['popup title', '.acq-details__title', 'The plan name. The same one the card shows.', 'cardDetails'],
      ['popup description', '.acq-details__description', 'The description in full. The card cuts it to fit and adds "… more"; here it is whole, exactly as you typed it.', 'cardDetails'],
      ['popup tabs', '.acq-details__tabs', 'The Content / Features switch.', 'cardDetails'],
      ['popup tab', '.acq-details__tab', 'One of the two tabs. The selected one carries a lighter background.', 'cardDetails'],
      ['popup list', '.acq-details__list', 'Whichever list the selected tab shows. The only part of the popup that scrolls, and it runs under the button rather than stopping above it.', 'cardDetails'],
      ['competition row', '.acq-details__row', 'One competition: its badge, its name and a line about it.', 'cardDetails'],
      ['competition badge', '.acq-details__logo', 'The 64 by 64 logo. Larger than the one on the card, which is 44.', 'cardDetails'],
      ['competition copy', '.acq-details__copy', 'The name and the line under it, stacked beside the badge.', 'cardDetails'],
      ['competition name', '.acq-details__row-title', 'The competition name, taken from the picker on the left.', 'cardDetails'],
      ['competition line', '.acq-details__row-blurb', 'One line about what that competition gives you. It belongs to the competition rather than to the plan, so it reads the same on every plan that carries it. Not editable yet.', 'cardDetails'],
      ['popup features list', '.acq-details__list--features', 'The Features tab: the same lines the card lists, at a larger size.', 'cardDetails'],
      ['popup feature row', '.acq-details__feature', 'One feature line.', 'cardDetails'],
      ['popup feature text', '.acq-details__feature-text', 'The words of one feature line.', 'cardDetails'],
      ['nothing to show', '.acq-details__empty', 'What a tab says when the plan has no competitions, or no feature lines.', 'cardDetails'],
      ['popup footer', '.acq-details__footer', 'The bar pinned to the bottom holding the button.', 'cardDetails'],
    ]],
    ['card-states', 'The card — rare states', 'both', 'Two things the card set does that are easy to forget exist.', [
      ['empty set message', '.acq-set__empty', 'What shows when there are no cards to draw at all.', 'cardStates'],
      ['measuring probe', '.acq-set__probe', 'An invisible copy of the text used to measure how tall things need to be, before the real cards are drawn. You never see it, but it is why the cards line up.', 'cardStates'],
      ['header probe', '.acq-card-header__probe', 'The same trick for one description on its own — it measures the full text so the card knows whether "… more" is needed.', 'cardStates'],
    ]],
    ['shell', 'Shell', 'archive', 'The frame around everything. Looks the same whichever view you are in.', [
      ['page', '.page.demo', 'The outermost wrapper. Carries the flags for panel-hidden and panel-collapsed, so anything that should react to those hangs off it.', 'shell'],
      ['top bar', '.demo__top', 'The strip across the very top. Stays put while everything below it scrolls.', 'shell'],
      ['brand strip', '.demo__brand', 'The left half of the top bar. It sits above the panel, and changes background to match whichever column is underneath it.', 'shell'],
      ['mark', '.demo__mark', 'The DAZN logo.', 'shell'],
      ['product title', '.demo__title', 'The words "Acquisition model".', 'shell'],
      ['beta chip', '.demo__beta', 'The small outlined BETA label next to the title.', 'shell'],
      ['collapse control', '.demo__collapse', 'The button that slides the left panel away and brings it back. It stays in the same spot either way, and the arrow flips.', 'shell'],
      ['status bar', '.demo__statusbar', 'The right half of the top bar. Tells you whether you can publish, and holds the buttons.', 'shell'],
      ['publish gate', '.demo__gate', 'Where the content stands, in four states: "Not ready for review" in red with how many situations are failing; "Ready for review" in green with how many were checked; "Waiting for product & UX approval" in amber once you have handed it over; and "Approved" in green after they say yes. It checks every market and storefront combination, not just the one you are looking at.', 'shell'],
      ['action buttons', '.demo__actions', 'The button group at the far right. Two in each view, and which two depends on the view.', 'shell'],
      ['save note', '.demo__savenote', 'A one-line message under the top bar confirming a save worked, or explaining why it did not. Only appears after you have saved.', 'shell'],
      ['body', '.demo__body', 'Everything under the top bar: the left column and the right column side by side.', 'shell'],
      ['rail', '.demo__rail', 'The track the panel slides inside. This is the thing that actually shrinks when you collapse — the panel keeps its width and gets clipped.', 'shell'],
      ['panel', '.demo__panel', 'The 360px left column. Scrolls on its own, and its contents change completely between the two views.', 'shell'],
      ['preview pane', '.demo__preview', 'The right column, showing what you are building. Scrolls on its own, and widens to fill the space when the panel is collapsed.', 'shell'],
    ]],
    ['ds', 'Design system', 'archive', 'Shared components. Change one and it changes everywhere it is used.', [
      ['text field', '.dz-field', 'The standard text box. 56 tall, with the label floating up when you type in it.', 'ds'],
      ['select field', '.dz-field--select', 'The dropdown. Same box with an arrow; its label sits up top permanently rather than floating.', 'ds'],
      ['toggle field', 'ToggleField', 'The on/off switch, used for Ultimate treatment and Apply discount. It comes in tones — gold for Ultimate, green for discount.', 'ds'],
      ['field label', '.dz-field__label', 'The label inside a field.', 'ds'],
      ['help text', '.dz-field__help', 'The explanatory line under a field.', 'ds'],
      ['button', '.dazn-btn', 'The button. Four looks — primary, secondary, subscribe, tertiary — and two heights.', 'ds'],
      ['button label', '.dazn-btn__label', 'The words inside a button, kept in their own element so an icon can sit beside them without shifting the text.', 'ds'],
      ['icon', '.dazn-icon', 'Any icon from the design system. Takes its colour from the text around it.', 'ds'],
    ]],
    ['ds-field', 'Design system — inside a field', 'archive', 'What a text box or dropdown is made of. Change these and every field in the tool changes.', [
      ['field body', '.dz-field__body', 'The bordered box itself — the thing that turns yellow on focus and red on an error.', 'dsField'],
      ['field leading', '.dz-field__leading', 'The slot before the text, for an icon like the discount tag.', 'dsField'],
      ['field control', '.dz-field__control', 'Wraps the label and the input together, so the label can float up over the text without moving it.', 'dsField'],
      ['field input', '.dz-field__input', 'Where you actually type. The dropdown uses the same element with a native select behind it.', 'dsField'],
      ['field trailing', '.dz-field__trailing', 'The slot after the text. Holds the chevron on a dropdown.', 'dsField'],
    ]],
    ['ds-toggle', 'Design system — inside a toggle', 'archive', 'What the on/off switch is made of — Ultimate treatment and Apply discount both use it.', [
      ['toggle block', '.tg', 'The whole switch with its label and hint.', 'dsToggle'],
      ['toggle row', '.tg__row', 'The clickable line: icon, label, and the switch itself.', 'dsToggle'],
      ['toggle leading', '.tg__leading', 'The slot for an icon before the label.', 'dsToggle'],
      ['toggle label', '.tg__label', 'The words naming what the switch does.', 'dsToggle'],
      ['toggle switch', '.dazn-toggle', 'The DS switch itself, at the right of the row. A button with role=switch, so it is one control rather than a hidden checkbox behind a drawn mark.', 'dsToggle'],
      ['toggle knob', '.dazn-toggle__knob', 'The circle that slides across it.', 'dsToggle'],
      ['toggle hint', '.tg__hint', 'An optional line under a toggle explaining what it does. Nothing passes one at the moment, so it renders nowhere — the slot is still part of the component.', 'dsToggle'],
    ]],
    ['routes', 'Routes', 'archive', 'Three pages. If you do not say which, I will assume demo 1.', [
      ['index', '/', 'The front door. Two links and nothing else.', 'routes'],
      ['demo 1', '/demo', 'The tool. Everything below lives here.', 'routes'],
      ['demo 2', '/demo2', 'The old first attempt, kept only so we can compare. It has its own components, which are not listed here.', 'routes'],
    ]],
  ];
