  // ── Areas ─────────────────────────────────────────────
  // Read off the components. [id, title, view, blurb, rows] — view is which
  // tab it appears under; 'both' shows in each.
  var AREAS = [
    ['panel-default', 'Panel', 'default', 'The left column when you are not editing a step. It asks which situation you are writing content for.', [
      ['context fields', '.demo__fields', 'The dropdowns as a set. Four of them normally, five when your answers describe more than one journey.', 'panelDefault'],
      ['market', 'dropdown 1', 'Which country you are writing for — or "Base", meaning the shared content every country starts from. The help text under it tells you which of the two you are doing.', 'panelDefault'],
      ['storefront', 'dropdown 2', 'Whether you are selling directly or through a partner like Movistar. Only partners that actually operate in the chosen country are listed.', 'panelDefault'],
      ['user status', 'dropdown 3', 'Who is buying: someone logged out, an existing customer, someone being migrated, or a TVE user. This choice decides which family of journeys you get.', 'panelDefault'],
      ['entry point', 'dropdown 4', 'Where they clicked in from. Narrowed by the answer above — someone being migrated never arrives from an Upgrade button.', 'panelDefault'],
      ['which journey', 'dropdown 5', 'Only appears when your four answers describe more than one journey, and lets you pick between them. Most combinations describe exactly one, so most of the time you never see it.', 'panelDefault'],
      ['user flow', '.uf', 'The journey written out as a numbered list. It is the same information as the tiles on the right, and they share a selection — clicking either opens the same step.', 'panelDefault'],
      ['flow heading', '.uf__title', 'The words "User flow:" above the list.', 'panelDefault'],
      ['flow list', '.uf__list', 'The numbered list itself.', 'panelDefault'],
      ['flow item', '.uf__item', 'One entry in the list, holding the step and the connector line drawn above it.', 'panelDefault'],
      ['flow row', '.uf__row', 'One step in the list. Highlights when selected, and dims when the journey skips it.', 'panelDefault'],
      ['flow dot', '.uf__dot', 'The circle at the left of a row. It holds a tick when that step has fields you can actually edit — today only Subscription does, and the list says so rather than pretending otherwise.', 'panelDefault'],
      ['flow name', '.uf__name', 'The step name.', 'panelDefault'],
      ['flow skip tag', '.uf__tag', 'A small "seeded" or "not here" on steps this journey skips. "Seeded" means the entry point already answered that question; "not here" means the step does not exist in this journey.', 'panelDefault'],
      ['flow edit button', '.uf__edit', 'The pencil that opens a step. Only on steps that have something to edit.', 'panelDefault'],
      ['flow connector', '.uf__link', 'The short line drawn between one row and the next, so the list reads as a sequence.', 'panelDefault'],
      ['reset progress', '.demo__reset', 'The link at the bottom. Throws away your local edits and reloads the content the app shipped with.', 'panelDefault'],
    ]],
    ['preview-default', 'Preview', 'default', 'The right column when you are not editing. Shows the whole journey at once.', [
      ['frames block', '.jf', 'The journey overview as a whole.', 'overview'],
      ['row caption', '.jf__caption', 'The line above the tiles: how many screens across how many steps.', 'overview'],
      ['drag hint', '.jf__hint', 'The reminder that you can drag a step sideways to reorder it, or hold alt and use the arrow keys.', 'overview'],
      ['reordered chip', '.jf__reordered', 'A small marker that appears once your order no longer matches the order drawn in Figma.', 'overview'],
      ['reset order', '.jf__reset', 'Puts the steps back into the Figma order.', 'overview'],
      ['frames row', '.jf__row', 'The row of screens that scrolls sideways.', 'overview'],
      ['step group', '.jf__step', 'One step together with all its screens. This is the block you drag when reordering.', 'overview'],
      ['step label', '.jf__step-name', 'The step name above its screens.', 'overview'],
      ['state count', '.jf__states', 'Says "· 3 states" when a step is drawn more than one way.', 'overview'],
      ['skip tag', '.jf__tag', 'A "seeded" or "not here" marker explaining why a step shows nothing.', 'overview'],
      ['tiles strip', '.jf__tiles', 'The screens belonging to one step, side by side.', 'overview'],
      ['tile cell', '.jf__cell', 'One tile and the caption under it, kept together so the caption tracks the screen it names.', 'overview'],
      ['step tile', '.jf__tile', 'One screen. Click it to edit that step.', 'overview'],
      ['tile number', '.jf__num', 'Where the step falls in the flow, beside its name. A step drawn three ways occupies three numbers and shows the span — 6–8 — so the last number in the row still equals the journey’s screen count.', 'overview'],
      ['thumbnail', '.jf__thumb', 'A live miniature of the real screen, built from your actual content. Sized to the proportions of a 375 by 812 phone.', 'overview'],
      ['thumbnail scaler', '.jf__thumb-scale', 'The layer inside the thumbnail that shrinks the screen. The screen renders at full size and this scales it down, so the miniature is the real thing rather than a separate small version that could drift from it.', 'overview'],
      ['phone status bar', '.jf__status', 'The iOS status bar across the top of a tile — the iOS/android component from Figma, drawn at the tile’s scale. Static, so it holds still while the screen scrolls beneath it; each frame’s own status bar is clipped off the export and this one drawn in its place.', 'overview'],
      ['status time', '.jf__status-time', 'The clock. Always 9:41, as the design has it.', 'overview'],
      ['notch spacer', '.jf__status-island', 'The gap the Dynamic Island sits in. It draws nothing and reserves 124px, which is why the clock sits left of centre rather than in the middle.', 'overview'],
      ['status levels', '.jf__status-levels', 'The signal, wifi and battery group at the right.', 'overview'],
      ['signal icon', '.jf__status-cell', 'Cellular bars, exported from the component.', 'overview'],
      ['wifi icon', '.jf__status-wifi', 'Wifi, exported from the component.', 'overview'],
      ['battery icon', '.jf__status-battery', 'Battery, exported from the component.', 'overview'],
      ['browser chrome', '.jf__chrome', 'The Safari address bar at the foot of a tile — the .Safari, iOS component from Figma, drawn at the tile’s scale so it is the design’s own geometry rather than an approximation. It is pinned rather than left in the picture, so it holds still while the screen scrolls behind it; each frame’s own bar is clipped off and this one drawn in its place.', 'overview'],
      ['chrome button', '.jf__chrome-btn', 'One of the two round 44px buttons either side of the address — back on the left, menu on the right.', 'overview'],
      ['address pill', '.jf__url', 'The rounded bar holding the site icon, the domain and the reload arrow.', 'overview'],
      ['site settings icon', '.jf__url-icon', 'The page-settings glyph at the left of the pill, exported from the Figma component.', 'overview'],
      ['address text', '.jf__url-text', 'The domain. Centred in the whole pill rather than in the gap between the icons, so a longer name stays centred.', 'overview'],
      ['reload icon', '.jf__url-reload', 'The refresh arrow at the right of the pill, exported from the Figma component.', 'overview'],
      ['browser menu', '.jf__dots', 'The three dots in the right-hand button. iOS draws it as an SF Symbol, which has no exported asset, so it is three dots at the symbol’s own size.', 'overview'],
      ['screen', '.jf__screen', 'Everything above the address bar, taking all the height the bar does not. A screen taller than that scrolls here rather than shrinking to fit — Checkout is 1321 tall, and fitting it would make the payment rows too small to read.', 'overview'],
      ['page clip', '.jf__page', 'Holds the exported picture and crops the Safari bar off its foot. Its height is the frame’s own height less that bar, at the tile’s scale, so it is set per screen rather than in the stylesheet.', 'overview'],
      ['screen artwork', '.jf__art', 'The screen exported from Figma, shown on steps that have not been built yet. Full tile width, natural height. It is a picture, so it does not change when you edit content — that is how you tell a built screen from one still to come.', 'overview'],
      ['frame name', '.jf__frame', 'The Figma frame name. The last resort, for a screen with neither a component nor an exported frame.', 'overview'],
      ['state label', '.jf__state', 'Which version of the screen a tile is — “standard”, “ultimate”. Sits under the tile rather than over it, where it covered the design it was labelling.', 'overview'],
    ]],
    ['actions-default', 'Action buttons', 'default', 'Two buttons at the top right when you are not editing a step.', [
      ['preview button', 'button 1 · secondary', 'Hides the panel so the preview fills the window. Press it again — it now says "Show panel" — to bring the panel back.', 'actionsDefault'],
      ['export button', 'button 2 · tertiary', 'Says "Export JSON". Downloads all the content as a file. Worth knowing: this is the shape this app stores, not yet the shape the live rule engine reads.', 'actionsDefault'],
    ]],
    ['panel-edit', 'Panel', 'edit', 'The left column once you have opened a step. Six groups of fields, all scoped to one country, one storefront and one way of paying.', [
      ['step heading', '.demo__head', 'The line at the top of the panel: the back arrow and the step title together.', 'panelEdit'],
      ['back arrow', '.demo__back', 'The chevron at the top left. It is the only thing on that line you can click, and it takes you back to the journey.', 'panelEdit'],
      ['step title', '.demo__step-title', 'The name of the step you have open. A heading, not a control — the arrow beside it is what takes you back.', 'panelEdit'],
      ['field group', '.demo__group', 'One titled block of fields. There are six of them.', 'panelEdit'],
      ['group title', '.demo__group-title', 'The heading on a group. Pricing adds the currency to its heading.', 'panelEdit'],
      ['plans group', 'group 1 · Plans', 'Which plan you are editing.', 'panelEdit'],
      ['header group', 'group 2 · Tier Name', 'The words at the top of the card.', 'panelEdit'],
      ['pricing group', 'group 3 · Pricing', 'What it costs and how you pay.', 'panelEdit'],
      ['add-on group', 'group 4 · Add-on', 'An extra product attached to the plan.', 'panelEdit'],
      ['competitions group', 'group 5 · Competitions', 'Which competition logos show on the card.', 'panelEdit'],
      ['features group', 'group 6 · Features', 'The bullet list of what you get.', 'panelEdit'],
    ]],
    ['group-plans', 'Plans group', 'edit', 'Group 1. Picks which plan the rest of the panel is about.', [
      ['plan tabs', '.ed-tabs', 'The row of plan names you switch between. Not a setting — it chooses which plan the whole panel below is editing.', 'groupPlans'],
      ['plan tab', '.ed-tab', 'One plan name. Dimmed when that plan is not sold in the situation you picked, and hovering it tells you why.', 'groupPlans'],
      ['plan not sold note', '.ed-absent', 'Appears when you are looking at a plan this situation does not sell. It says why, and reassures you that your edits still apply everywhere the plan does sell.', 'groupPlans'],
      ['no plans message', '.ed-placeholder · plans', 'What the panel says instead of a form when the content has no plans at all.', 'groupPlans'],
    ]],
    ['group-header', 'Header group', 'edit', 'Group 2. The words at the top of the card.', [
      ['badge field', 'Badge', 'The words on the badge. Editable — type what it should say. Whether a badge shows at all is still the Highlighted Tier switch’s call, and leaving this empty falls back to “BEST EXPERIENCE” rather than shipping a blank ribbon.', 'groupHeader'],
      ['ultimate toggle', 'Highlighted Tier', 'The switch that makes this the standout plan: gold outline, badge and gold button. Only one plan in a set may have it.', 'groupHeader'],
      ['plan name field', 'Tier name', 'The public name of the plan. One value that appears in three places — the card heading, the button, and the add-on label.', 'groupHeader'],
      ['AI pill', '.ai-pill', 'The AI half of the source tabs — the product’s own pill, with the sparkle and the yellow-to-purple gradient edge. Two stacked backgrounds make that edge: a flat fill clipped to the padding box, the gradient clipped to the border box, showing through a transparent 1px border. Unselected it dims rather than changing shape.', 'groupHeader'],
      ['AI sparkle', '.ai-pill__mark', 'The four-point glyph inside the AI pill. A flex box rather than a plain wrapper, so the icon centres instead of resting on a text baseline.', 'groupHeader'],
      ['source tabs', '.ed-source', 'Two tabs hard right above a copy field: AI or Custom. Used twice — over the Description and over the Price explainer. Custom is the default, and it is what copy written before the choice existed counts as. Choosing AI hands that field to the assistant and makes it read-only here.', 'groupHeader'],
      ['description field', 'Description', 'The paragraph under the plan name. Type the whole thing; never shorten it yourself, because the card measures the space and adds "… more" where it needs to.', 'groupHeader'],
    ]],
    ['group-pricing', 'Pricing group', 'edit', 'Group 3. What it costs. Every price here belongs to one way of paying.', [
      ['cadence field', 'How to pay', 'Monthly Flex, Instalments Annual, or Annual Upfront. Changing it changes which prices you are editing — a plan with no price here simply is not sold that way.', 'groupPricing'],
      ['apply discount toggle', 'Apply discount', 'Turns on a promotional price. Switching it on fills in a starting discount price for you, twenty percent under standard, which you can then change.', 'groupPricing'],
      ['standard price field', 'Full price', 'The undiscounted price, in the currency of the country you picked.', 'groupPricing'],
      ['discount price field', 'Discount price', 'The promotional price. Only appears when the discount is on, and it turns red if you type a number at or above the standard price, because that is not a discount.', 'groupPricing'],
      ['button field', 'Button', 'What the card’s button says. Three forms: the plain “Get Ultimate”, or that plus the saving as money or as a percentage. The menu is labelled with the button each option produces rather than naming a setting. Only appears where there is a discount — the saving is what the other two forms are for.', 'groupPricing'],
      ['price explainer field', 'Price explainer', 'The sentence under the price — “For the first 3 months, then $34.99/monthly”. Only appears where there is a discount to explain. Editable, with the same AI or Custom choice as the Description; empty falls back to the sentence built from the intro months, the full price and the cadence.', 'groupPricing'],
      ['not sold at this cadence', '.ed-placeholder · pricing', 'Replaces the price fields when this plan is not sold at the chosen cadence. It says plainly that this is a fact about the plan, not something missing that you need to fill in.', 'groupPricing'],
    ]],
    ['group-addon', 'Add-on group', 'edit', 'Group 4. An extra product attached to this price. Hidden for now — the group is not in the panel and the panel is not on the card, both off one switch (SHOW_ADDON). The fields and the catalogue are intact underneath.', [
      ['add-on field', 'Add-on', 'Which extra product goes with this plan, and whether it is sold separately or included in the price. Each add-on appears twice in the list, once as "sold" and once as "bundled" — it can never be both.', 'groupAddon'],
      ['paid-for field', 'How it is paid for', 'Only when the add-on is sold rather than bundled. Either a one-off payment, or a discount code the customer redeems.', 'groupAddon'],
      ['discount percent field', 'Discount percent', 'Only when the add-on is sold with a discount code. How much off, as a number between 1 and 99.', 'groupAddon'],
      ['no offer note', '.ed-placeholder · add-on', 'Replaces the add-on fields when the plan has no price at this cadence, since there is nothing to attach an add-on to.', 'groupAddon'],
    ]],
    ['group-comps', 'Competitions group', 'edit', 'Group 5. Which competition logos appear on the card.', [
      ['logo picker', '.ed-logos', 'The grid of competition logos you click to switch on and off.', 'groupComps'],
      ['logo button', '.ed-logo', 'One competition. Hovering shows its name.', 'groupComps'],
      ['competitions total field', 'Total number of competitions', 'How many competitions the plan carries in total, which is usually more than the logos shown. The card works out the "+5" tile from this number minus the logos on display.', 'groupComps'],
    ]],
    ['group-features', 'Features group', 'edit', 'Group 6. The bullet list of what you get.', [
      ['feature row', '.demo__feature', 'One line of the list, with its picker and — when the line is a custom one — the box to type it in.', 'groupFeatures'],
      ['feature picker', 'Feature 1, 2, 3…', 'Choose a line from the shared library, or pick "Custom line…" at the bottom to write a new one. Retired lines are still listed, marked "(retired)", so old content keeps working.', 'groupFeatures'],
      ['line text field', 'Line text', 'Where you type a custom line. What you write is saved into the shared library, so it can be reused on other plans.', 'groupFeatures'],
      ['remove feature', '.demo__feature-remove', 'Takes that line off this plan. It stays in the library.', 'groupFeatures'],
      ['add feature', 'Add feature', 'Adds another line to the list.', 'groupFeatures'],
    ]],
    ['preview-edit', 'Preview', 'edit', 'The right column once you have opened a step. Shows just that one screen.', [
      ['step preview', '.jy', 'The step preview as a whole.', 'stepview'],
      ['entry line', '.jy__entry', 'The line of context above the screen.', 'stepview'],
      ['step name', '.jy__step-name', 'Which step you are looking at.', 'stepview'],
      ['step meta', '.jy__meta', 'Where this step sits in the flow, what the customer clicked to get here, and how many plans are in the set.', 'stepview'],
      ['inbound seeds', '.jy__seeds', 'What the entry point already decided before the customer got here — so you know which questions this screen no longer has to ask.', 'stepview'],
      ['viewport', '.jy__viewport', 'The frame the real screen renders inside. Sized to a 375-wide phone when the set is a mobile one.', 'stepview'],
      ['placeholder screen', '.jy__placeholder', 'What you see instead of a real screen when that step has not been built yet. It tells you everything known about the screen so far.', 'stepview'],
      ['placeholder frame name', '.jy__frame', 'The name of the Figma frame this screen will be built from.', 'stepview'],
      ['placeholder states', '.jy__states', 'The different versions this screen is drawn in.', 'stepview'],
      ['placeholder gates', '.jy__requires', 'The conditions the real product checks before showing this screen.', 'stepview'],
      ['placeholder note', '.jy__note', 'A free note about the screen. The same style also carries the message when a journey has no steps in the chosen country.', 'stepview'],
      ['placeholder warning', '.jy__todo', 'The line reading "Placeholder — this screen isn’t built yet."', 'stepview'],
    ]],
    ['actions-edit', 'Action buttons', 'edit', 'The buttons at the top right once you have opened a step. Settings sits third here too.', [
      ['save button', 'button 1 · primary', 'Says "Save changes". Asks you what changed, then publishes to the shared copy. Greyed out when there is nothing new to save, and reads "Saving…" while it works. Your typing is kept locally the whole time — this button is about sharing it, not about not losing it.', 'actionsEdit'],
      ['exit button', 'button 2 · secondary', 'Says "Exit edit mode". Closes the step and goes back to the journey overview. It does not discard anything.', 'actionsEdit'],
    ]],
    ['card', 'The card', 'both', 'The plan card itself. This is what renders in the preview and inside every thumbnail.', [
      ['set scroller', '.acq-set-scroll', 'The scrolling wrapper around the row of cards, for when they do not all fit.', 'card'],
      ['card set', '.acq-set', 'The row of cards. It measures all of them and gives them one shared description height and one shared card height, so they line up.', 'card'],
      ['card', '.acq-card', 'One plan card. Gains a gold outline when it is the Ultimate one.', 'card'],
      ['badge', '.acq-card__eyebrow', 'The "BEST EXPERIENCE" label on the top edge. Comes from the Ultimate toggle, and only one card in a set can have it.', 'card'],
      ['card body', '.acq-card__body', 'Everything inside the card except the footer.', 'card'],
      ['card header', '.acq-card-header', 'The plan name and description together.', 'card'],
      ['plan name', '.acq-card-header__title', 'The name at the top. Gets the gold treatment on the Ultimate card.', 'card'],
      ['description', '.acq-card-header__description', 'The paragraph. Measured against the other cards and cut to the shared height.', 'card'],
      ['more button', '.acq-card-header__more', 'The "… more" link, which only appears when the description is too long to fit.', 'card'],
      ['card divider', '.acq-card__divider', 'The line between the header and the price.', 'card'],
      ['pricing', '.acq-pricing', 'The whole price block.', 'card'],
      ['price caption', '.acq-pricing__caption', 'The small "Starts at" above the number.', 'card'],
      ['price row', '.acq-pricing__row', 'The line holding the price and the struck-through price side by side.', 'card'],
      ['price', '.acq-pricing__price', 'The number people actually read.', 'card'],
      ['crossed price', '.acq-pricing__crossed', 'The struck-through standard price, shown only when there is a discount.', 'card'],
      ['price explainer', '.acq-pricing__extra', 'The sentence under the price explaining the offer.', 'card'],
      ['instalment line', '.acq-pricing__installment', 'The line spelling out the monthly instalment on an annual plan.', 'card'],
      ['plan CTA', '.acq-plan-cta', 'The savings line and the Get button together as one block.', 'card'],
      ['savings ribbon', '.acq-plan-cta__eyebrow', 'The "Save up to €108 / year" line. Worked out from the two prices, not typed.', 'card'],
      ['get button', '.acq-plan-cta__stack', 'The button that starts the purchase. Gold on the Ultimate card.', 'card'],
      ['logo tiles', '.acq-logo-tiles', 'The row of competition logos, in the order they were picked.', 'card'],
      ['logo tile', '.acq-logo-tiles__tile', 'One competition logo.', 'card'],
      ['overflow tile', '.acq-logo-tiles__tile--overflow', 'The "+5" tile. Worked out from the total you entered minus the logos on show — not something you pick.', 'card'],
      ['add-on panel', '.acq-addon', 'The block advertising the extra product.', 'card'],
      ['features list', '.acq-features', 'The bullet list as a block.', 'card'],
      ['card feature row', '.acq-feature', 'One bullet: an icon and a line of text.', 'card'],
      ['feature text', '.acq-feature__text', 'The words of one bullet.', 'card'],
      ['card footer', '.acq-card__footer', 'The "All features & content" bar across the bottom, edge to edge.', 'card'],
    ]],
    ['card-addon', 'The card — add-on panel', 'both', 'The inside of the add-on block on the card. Hidden for now, with the rest of the add-on — these are what it draws when it comes back.', [
      ['add-on content', '.acq-addon__content', 'The artwork and the words together, above the divider.', 'cardAddon'],
      ['add-on artwork', '.acq-addon__image', 'The picture of the add-on.', 'cardAddon'],
      ['add-on text', '.acq-addon__text', 'The title and subtitle stacked beside the artwork.', 'cardAddon'],
      ['add-on title', '.acq-addon__title', 'Its name.', 'cardAddon'],
      ['add-on subtitle', '.acq-addon__subtitle', 'The line under the name.', 'cardAddon'],
      ['add-on status', '.acq-addon__status', 'How it is offered. Three versions: included in the price, a payment, or a discount code — and the styling differs for each.', 'cardAddon'],
      ['add-on divider', '.acq-addon__divider', 'The line inside the block.', 'cardAddon'],
      ['add-on footer', '.acq-addon__footer', 'The bottom row of the block.', 'cardAddon'],
    ]],
    ['card-states', 'The card — rare states', 'both', 'Two things the card set does that are easy to forget exist.', [
      ['empty set message', '.acq-set__empty', 'What shows when there are no cards to draw at all.', 'cardStates'],
      ['measuring probe', '.acq-set__probe', 'An invisible copy of the text used to measure how tall things need to be, before the real cards are drawn. You never see it, but it is why the cards line up.', 'cardStates'],
      ['header probe', '.acq-card-header__probe', 'The same trick for one description on its own — it measures the full text so the card knows whether "… more" is needed.', 'cardStates'],
    ]],
    ['shell', 'Shell', 'archive', 'The frame around everything. Looks the same whichever view you are in.', [
      ['page', '.page.demo', 'The outermost wrapper. Carries the flags for panel-hidden and panel-collapsed, so anything that should react to those hangs off it.', 'shell'],
      ['top bar', '.demo__top', 'The strip across the very top. Stays put while everything below it scrolls.', 'shell'],
      ['brand strip', '.demo__brand', 'The left half of the top bar. It sits above the panel, and changes background to match whichever column is underneath it.', 'shell'],
      ['mark', '.demo__mark', 'The DAZN logo.', 'shell'],
      ['product title', '.demo__title', 'The words "Acquisition model".', 'shell'],
      ['beta chip', '.demo__beta', 'The small outlined BETA label next to the title.', 'shell'],
      ['collapse control', '.demo__collapse', 'The button that slides the left panel away and brings it back. It stays in the same spot either way, and the arrow flips.', 'shell'],
      ['status bar', '.demo__statusbar', 'The right half of the top bar. Tells you whether you can publish, and holds the buttons.', 'shell'],
      ['publish gate', '.demo__gate', 'Says either "Publish ready" with the number of situations checked, or "Publish blocked" with how many are failing. It checks every market and storefront combination, not just the one you are looking at.', 'shell'],
      ['action buttons', '.demo__actions', 'The button group at the far right. Two in each view, and which two depends on the view.', 'shell'],
      ['save note', '.demo__savenote', 'A one-line message under the top bar confirming a save worked, or explaining why it did not. Only appears after you have saved.', 'shell'],
      ['body', '.demo__body', 'Everything under the top bar: the left column and the right column side by side.', 'shell'],
      ['rail', '.demo__rail', 'The track the panel slides inside. This is the thing that actually shrinks when you collapse — the panel keeps its width and gets clipped.', 'shell'],
      ['panel', '.demo__panel', 'The 360px left column. Scrolls on its own, and its contents change completely between the two views.', 'shell'],
      ['preview pane', '.demo__preview', 'The right column, showing what you are building. Scrolls on its own, and widens to fill the space when the panel is collapsed.', 'shell'],
    ]],
    ['ds', 'Design system', 'archive', 'Shared components. Change one and it changes everywhere it is used.', [
      ['text field', '.dz-field', 'The standard text box. 56 tall, with the label floating up when you type in it.', 'ds'],
      ['select field', '.dz-field--select', 'The dropdown. Same box with an arrow; its label sits up top permanently rather than floating.', 'ds'],
      ['toggle field', 'ToggleField', 'The on/off switch, used for Ultimate treatment and Apply discount. It comes in tones — gold for Ultimate, green for discount.', 'ds'],
      ['field label', '.dz-field__label', 'The label inside a field.', 'ds'],
      ['help text', '.dz-field__help', 'The explanatory line under a field.', 'ds'],
      ['button', '.dazn-btn', 'The button. Four looks — primary, secondary, subscribe, tertiary — and two heights.', 'ds'],
      ['button label', '.dazn-btn__label', 'The words inside a button, kept in their own element so an icon can sit beside them without shifting the text.', 'ds'],
      ['icon', '.dazn-icon', 'Any icon from the design system. Takes its colour from the text around it.', 'ds'],
    ]],
    ['ds-field', 'Design system — inside a field', 'archive', 'What a text box or dropdown is made of. Change these and every field in the tool changes.', [
      ['field body', '.dz-field__body', 'The bordered box itself — the thing that turns yellow on focus and red on an error.', 'dsField'],
      ['field leading', '.dz-field__leading', 'The slot before the text, for an icon like the discount tag.', 'dsField'],
      ['field control', '.dz-field__control', 'Wraps the label and the input together, so the label can float up over the text without moving it.', 'dsField'],
      ['field input', '.dz-field__input', 'Where you actually type. The dropdown uses the same element with a native select behind it.', 'dsField'],
      ['field trailing', '.dz-field__trailing', 'The slot after the text. Holds the chevron on a dropdown.', 'dsField'],
    ]],
    ['ds-toggle', 'Design system — inside a toggle', 'archive', 'What the on/off switch is made of — Ultimate treatment and Apply discount both use it.', [
      ['toggle block', '.tg', 'The whole switch with its label and hint.', 'dsToggle'],
      ['toggle row', '.tg__row', 'The clickable line: icon, label, and the switch itself.', 'dsToggle'],
      ['toggle leading', '.tg__leading', 'The slot for an icon before the label.', 'dsToggle'],
      ['toggle label', '.tg__label', 'The words naming what the switch does.', 'dsToggle'],
      ['toggle switch', '.dazn-toggle', 'The DS switch itself, at the right of the row. A button with role=switch, so it is one control rather than a hidden checkbox behind a drawn mark.', 'dsToggle'],
      ['toggle knob', '.dazn-toggle__knob', 'The circle that slides across it.', 'dsToggle'],
      ['toggle hint', '.tg__hint', 'An optional line under a toggle explaining what it does. Nothing passes one at the moment, so it renders nowhere — the slot is still part of the component.', 'dsToggle'],
    ]],
    ['routes', 'Routes', 'archive', 'Three pages. If you do not say which, I will assume demo 1.', [
      ['index', '/', 'The front door. Two links and nothing else.', 'routes'],
      ['demo 1', '/demo', 'The tool. Everything below lives here.', 'routes'],
      ['demo 2', '/demo2', 'The old first attempt, kept only so we can compare. It has its own components, which are not listed here.', 'routes'],
    ]],
  ];
